version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Porta padrão do Vite
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
